name: e_commercee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0

 #--------[Packages]----
dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8

  # UTILITIES
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1

  #state Management
  get: ^4.7.2



#-----------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true

    #----------[Assets]--------
  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/categories/
    - assets/banners/
    - assets/products/


  #---------[Fonts]-------
fonts:
  - family: "Nunito"
    fonts:
      - asset: assets/fonts/Nunito-Light.ttf
        weight: 300
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito-Italic.ttf
        style: italic
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 800
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
